// @d-op/shared — explicit stable contract surface (task 3).
// Named re-exports only; tasks 6/7/11/12 consume these names.

export type {
  ActivateOperation,
  ApiError,
  ApiErrorCode,
  ApiErrorDetails,
  CreateAck,
  DeletePlaylistBody,
  GetPlaylistResponse,
  IdempotencyKey,
  ImportNotifyBody,
  ListQuery,
  ListResponse,
  PatchAck,
  PatchPlaylistBody,
  PublicSource,
  Ranking,
  ReplaceOperation,
  Revision,
} from "./api"
export {
  ActivateOperationSchema,
  API_BASE_PATH,
  API_ERROR_CODES,
  ApiErrorSchema,
  apiSuccessSchema,
  CreateAckSchema,
  DeletePlaylistBodySchema,
  GetPlaylistResponseSchema,
  IDEMPOTENCY_KEY_HEADER,
  IdempotencyKeySchema,
  ImportNotifyBodySchema,
  LIST_SORTS,
  ListQuerySchema,
  ListResponseSchema,
  PatchAckSchema,
  PatchPlaylistBodySchema,
  PublicSourceSchema,
  RANK_MODES,
  RANK_WINDOWS,
  RankingSchema,
  ReplaceOperationSchema,
  RevisionSchema,
} from "./api"
export type {
  BackgroundRequest,
  BridgeReply,
  ChaptersFound,
  ExtensionMessage,
  PageCommand,
  PlayerCommand,
  SenderSurface,
} from "./bridge"
export {
  assertMessageAllowedOnSurface,
  BackgroundRequestSchema,
  BridgeReplySchema,
  CapabilityLeakError,
  ChaptersFoundSchema,
  describeExtensionMessage,
  ExtensionMessageSchema,
  isPrivilegedSurface,
  newCorrelationId,
  PAGE_MESSAGE_SOURCE,
  PageCommandSchema,
  PlayerCommandSchema,
  SENDER_SURFACES,
  VAULT_PRIVILEGED_SURFACES,
} from "./bridge"
export type {
  ContentHashHex,
  IsoDateTime,
  ManageSecret,
  ShareId,
} from "./limits"
export {
  ACTIVATION_EXPIRES_AFTER_MS,
  assertNever,
  COLLECTION_LIMIT_DEFAULT,
  COLLECTION_LIMIT_MAX,
  COLLECTION_LIMIT_MIN,
  COLLECTION_QUERY_MAX,
  CONTENT_HASH_LENGTH,
  ContentHashSchema,
  collapseWhitespace,
  DAY_BUCKET_RETENTION_DAYS,
  DISCOVERY_SNAPSHOT_MAX_IDS,
  DISCOVERY_SNAPSHOT_TTL_MS,
  FIRST_PAGE_SNAPSHOT_REUSE_MS,
  IMPORT_RECEIPT_TTL_MS,
  IsoDateTimeSchema,
  issuePaths,
  LEGACY_MIGRATION_VERSION,
  LEGACY_STORAGE_KEYS,
  LOCAL_IMPORT_FILE_MAX_BYTES,
  LOCAL_IMPORT_MAX_ITEMS,
  LOCAL_SCHEMA_VERSION,
  LOCAL_STATE_KEY,
  MANAGE_SECRET_LENGTH,
  MAX_OPERATION_RECEIPTS,
  ManageSecretSchema,
  MIN_POSITIVE_PLAYLISTS,
  MsIntSchema,
  MUTATION_RECEIPT_TTL_MS,
  normalizedStringSchema,
  OPAQUE_ID_PATTERN,
  opaqueIdSchema,
  PLAYBACK_URL_PATH,
  RANK_WINDOWS_DAYS,
  RATE_LIMITS,
  SERVER_REVISION_START,
  SHARE_AUTHOR_MAX,
  SHARE_DESCRIPTION_MAX,
  SHARE_EPISODE_NUMBER_MAX,
  SHARE_ID_LENGTH,
  SHARE_ITEM_TITLE_MAX,
  SHARE_ITEMS_MAX,
  SHARE_ITEMS_MIN,
  SHARE_PART_ID_MAX,
  SHARE_PART_ID_MIN,
  SHARE_RANGE_MAX_END_MS,
  SHARE_RANGE_NAME_MAX,
  SHARE_REQUEST_BODY_MAX_BYTES,
  SHARE_SCHEMA_VERSION,
  SHARE_TAG_MAX,
  SHARE_TAG_MIN,
  SHARE_TAGS_MAX,
  SHARE_TITLE_MAX,
  SHARE_TITLE_MIN,
  ShareIdSchema,
  SUPPORTED_ORIGINS,
  sortCanonicalTags,
  TRANSIENT_STATE_KEY,
} from "./limits"
export type {
  LegacyImportResult,
  LocalCommand,
  LocalItem,
  LocalPlaylist,
  LocalPreferences,
  LocalRange,
  LocalV2State,
  MigrationRecovery,
  OperationReceipt,
  PendingCreate,
  PublicationRecord,
  PublicationState,
  QuarantineEntry,
  SafeExportEnvelope,
  StorageRequest,
  TransientOpEdMode,
  TransientPlayback,
  TransientPlayerWindow,
  TransientState,
} from "./local"
export {
  buildSafeExport,
  checkLocalImportBudget,
  FutureExportVersionError,
  LocalCommandSchema,
  LocalItemSchema,
  LocalPlaylistSchema,
  LocalPreferencesSchema,
  LocalRangeSchema,
  LocalV2StateSchema,
  MalformedExportError,
  MigrationRecoverySchema,
  mapLegacyRangeTypeToName,
  OperationReceiptSchema,
  PendingCreateSchema,
  PublicationRecordSchema,
  PublicationStateSchema,
  parseLegacyLibrary,
  QuarantineEntrySchema,
  repairMissingId,
  SafeExportEnvelopeSchema,
  StorageRequestSchema,
  TransientOpEdModeSchema,
  TransientPlaybackSchema,
  TransientPlayerWindowSchema,
  TransientStateSchema,
} from "./local"
export type {
  ContentHash,
  DerivedFrom,
  PublicProjection,
  PublishableLocalItem,
  PublishableLocalPlaylist,
  PublishMetadata,
  SharedPlaylist,
  ShareItem,
  ShareRange,
  UnpublishableReason,
  UnpublishableReasonCode,
} from "./share"
export {
  buildPlaybackUrl,
  canonicalBytes,
  canonicalString,
  checkShareBodySize,
  contentHashOf,
  DerivedFromSchema,
  InvalidCanonicalValueError,
  InvalidPartIdError,
  isDirty,
  OversizePayloadError,
  PublishMetadataSchema,
  projectPublicPlaylist,
  SharedPlaylistSchema,
  ShareItemSchema,
  ShareRangeSchema,
  sha256HexBytes,
  toPublishProjection,
  UnpublishablePlaylistError,
} from "./share"
