#!/usr/bin/env node
// Deploy-time version bumper, used by .github/workflows/deploy.yml.
//
// The site badge (apps/web/src/site-version.ts) and every release artifact
// name derive from the workspace package.json versions, which
// verify-artifacts requires to be identical — so all four are always
// bumped together, never selectively. Prints the resulting version to
// stdout so the caller can feed it to git/GITHUB_OUTPUT.
//
//   node scripts/bump-version.mjs           # patch bump: 2.0.1 -> 2.0.2
//   node scripts/bump-version.mjs --to 2.0.5
//
// `--to` sets an explicit version; the deploy workflow uses it to replay a
// bump inside a later job when the bump commit could not be pushed (e.g. a
// protected main branch), so the deployed badge still matches the computed
// version even though the repository file could not record it yet.
// bun.lock workspace entries are regenerated by the `bun install` step the
// workflow runs right after this script — never edit the lockfile here.

import { readFileSync, writeFileSync } from "node:fs"

const PACKAGE_JSONS = [
  "package.json",
  "apps/extension/package.json",
  "apps/web/package.json",
  "packages/shared/package.json",
]

const toIndex = process.argv.indexOf("--to")
let next
if (toIndex !== -1) {
  next = process.argv[toIndex + 1] ?? ""
  if (!/^\d+\.\d+\.\d+$/.test(next)) {
    console.error("bump-version: --to requires an X.Y.Z version")
    process.exit(2)
  }
} else {
  const current = JSON.parse(readFileSync("apps/extension/package.json", "utf8")).version
  const match = /^(\d+)\.(\d+)\.(\d+)$/.exec(current)
  if (!match) {
    console.error(`bump-version: unparseable version "${current}"`)
    process.exit(2)
  }
  next = `${match[1]}.${match[2]}.${Number(match[3]) + 1}`
}

for (const file of PACKAGE_JSONS) {
  const pkg = JSON.parse(readFileSync(file, "utf8"))
  pkg.version = next
  writeFileSync(file, `${JSON.stringify(pkg, null, 2)}\n`)
}
console.log(next)
