#!/usr/bin/env node
// Release-time version bumper — the manual helper for the "bump versions
// in a normal PR" step in docs/release.md.
//
// apps/extension/package.json is the single version source; the site badge
// (apps/web/src/site-version.ts) and every release artifact name derive
// from the workspace package.json versions, which verify-artifacts
// requires to be identical — so all four are always bumped together,
// never selectively. Prints the resulting version to stdout.
//
//   node scripts/bump-version.mjs           # patch bump: 2.0.1 -> 2.0.2
//   node scripts/bump-version.mjs --to 2.0.5
//   node scripts/bump-version.mjs --print   # print the next patch version without writing
//
// bun.lock workspace entries are regenerated by running `bun install`
// after this script — never edit the lockfile here.

import { readFileSync, writeFileSync } from "node:fs"

const PACKAGE_JSONS = [
  "package.json",
  "apps/extension/package.json",
  "apps/web/package.json",
  "packages/shared/package.json",
]

const toIndex = process.argv.indexOf("--to")
let next
if (toIndex !== -1) {
  next = process.argv[toIndex + 1] ?? ""
  if (!/^\d+\.\d+\.\d+$/.test(next)) {
    console.error("bump-version: --to requires an X.Y.Z version")
    process.exit(2)
  }
} else {
  const current = JSON.parse(readFileSync("apps/extension/package.json", "utf8")).version
  const match = /^(\d+)\.(\d+)\.(\d+)$/.exec(current)
  if (!match) {
    console.error(`bump-version: unparseable version "${current}"`)
    process.exit(2)
  }
  next = `${match[1]}.${match[2]}.${Number(match[3]) + 1}`
}

if (process.argv.includes("--print")) {
  console.log(next)
  process.exit(0)
}

for (const file of PACKAGE_JSONS) {
  const pkg = JSON.parse(readFileSync(file, "utf8"))
  pkg.version = next
  writeFileSync(file, `${JSON.stringify(pkg, null, 2)}\n`)
}
console.log(next)
